import {
  FaUsers,
  FaBolt,
  FaServer,
  FaMobileAlt,
  FaShieldAlt,
  FaGamepad,
  FaTrophy,
} from "react-icons/fa";

export const PROJECTS_DATA = [
  {
    title: "Nirmalaitours - Car Rental Booking Platform",
    desc: "Full-stack car rental platform with customer booking and admin management system.",
    longDesc:
      "A comprehensive MERN stack car rental platform serving Nagpur and surrounding areas. Customers can browse available vehicles, calculate real-time pricing, book cars for local or outstation trips, and receive instant WhatsApp confirmations. The platform features a powerful admin dashboard for fleet management, booking oversight, customer insights, and notification management.",
    tags: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "JWT Auth",
      "Tailwind CSS",
      "Mongoose",
      "REST API",
      "React Router",
      "Netlify",
      "Render",
      "Vite",
    ],
    live: "https://nirmalaitours.netlify.app",
    github: "https://github.com/anshumankharbade/nirmalaitours",
    featured: true,
    views: 280,
    gradient: "from-orange-500/20 to-red-500/20",
    metrics: [
      {
        label: "Active Users",
        value: "500+",
        icon: <FaUsers />,
        color: "text-green-400",
      },
      {
        label: "Booking Response",
        value: "<1s",
        icon: <FaBolt />,
        color: "text-blue-400",
      },
      {
        label: "Uptime",
        value: "99.9%",
        icon: <FaServer />,
        color: "text-yellow-400",
      },
      {
        label: "WhatsApp Integration",
        value: "Instant",
        icon: <FaMobileAlt />,
        color: "text-green-400",
      },
    ],
    challenges: [
      "Implementing real-time price calculation with dynamic extra km and overnight halt charges",
      "Building a responsive admin dashboard with comprehensive booking management",
      "Integrating WhatsApp API for instant booking confirmations",
      "Handling complex date validation for same-day outstation trips",
      "Managing CORS and deployment configurations across Netlify and Render",
    ],
    screenshots: ["/images/nirmalaitours.png", "/images/nirmalaitours.png"],
    features: [
      "Customer car browsing with detailed specifications and real-time availability",
      "Smart price calculator with base fare, extra km, driver allowance, and halt charges",
      "Secure user authentication with JWT and role-based access (customer/admin)",
      "Admin dashboard with fleet management, booking oversight, and revenue tracking",
      "Instant WhatsApp booking confirmations with detailed trip information",
      "Booking history with status tracking and cancellation requests",
      "Responsive design optimized for mobile, tablet, and desktop",
      "Notification system for real-time booking updates",
    ],
  },
  {
    title: "QikMeds - Healthcare Platform",
    desc: "Full-stack healthcare app with medicine management, doctor consultations & pharmacy services.",
    longDesc:
      "A comprehensive MERN stack healthcare platform enabling users to manage medicines, book doctor consultations, and access pharmacy services. Features include real-time chat, prescription management, secure payment integration, and admin dashboard for managing healthcare services.",
    tags: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "JWT Auth",
      "Socket.io",
      "Razorpay",
      "Tailwind CSS",
      "Redux",
      "Mongoose",
    ],
    live: "https://qikmeds.vercel.app/",
    github: "https://github.com/anshumankharbade/qikmeds-frontend",
    backend: "https://github.com/anshumankharbade/qikmeds-backend",
    featured: true,
    views: 320,
    gradient: "from-teal-500/20 to-cyan-500/20",
    metrics: [
      {
        label: "Active Users",
        value: "1000+",
        icon: <FaUsers />,
        color: "text-green-400",
      },
      {
        label: "Response Time",
        value: "0.8s",
        icon: <FaBolt />,
        color: "text-blue-400",
      },
      {
        label: "Uptime",
        value: "99.9%",
        icon: <FaServer />,
        color: "text-yellow-400",
      },
      {
        label: "Data Security",
        value: "A+",
        icon: <FaShieldAlt />,
        color: "text-purple-400",
      },
    ],
    challenges: [
      "Implementing real-time doctor-patient chat with Socket.io",
      "Secure payment gateway integration with Razorpay",
      "Managing prescription data with privacy considerations",
      "Handling medicine inventory across multiple pharmacies",
    ],
    screenshots: ["/images/qikmeds.jpg", "/images/qikmeds.jpg"],
    features: [
      "Medicine search and order management system",
      "Doctor consultation booking with calendar",
      "Real-time chat with healthcare professionals",
      "Prescription upload and digital management",
      "Secure payment integration with multiple options",
      "Order tracking and history with notifications",
      "Multi-vendor pharmacy dashboard",
      "Admin panel for user and content management",
    ],
  },
  {
    title: "LockR - Password Manager",
    desc: "A secure password manager with local credential storage, copy/edit/delete functionality.",
    longDesc:
      "A full-featured password management application that securely stores credentials locally in the browser. Features include AES encryption simulation, password strength analysis, and intuitive UI for managing multiple accounts.",
    tags: [
      "React",
      "Local Storage",
      "Tailwind CSS",
      "Context API",
      "Responsive Design",
      "AES Encryption",
    ],
    live: "https://lockr-pi.vercel.app/",
    github: "https://github.com/anshumankharbade/lockr",
    featured: true,
    views: 150,
    gradient: "from-purple-500/20 to-blue-500/20",
    metrics: [
      {
        label: "Load Time",
        value: "1.2s",
        icon: <FaBolt />,
        color: "text-green-400",
      },
      {
        label: "Users",
        value: "50+",
        icon: <FaUsers />,
        color: "text-blue-400",
      },
      {
        label: "Mobile Score",
        value: "98%",
        icon: <FaMobileAlt />,
        color: "text-yellow-400",
      },
    ],
    challenges: [
      "Implementing secure local storage without backend",
      "Creating intuitive UI for password management",
      "Ensuring data persistence across sessions",
    ],
    screenshots: ["/images/lockr.png", "/images/lockr.png"],
    features: [
      "Secure local credential storage",
      "Copy/edit/delete functionality",
      "Password strength indicator",
      "Search and filter capabilities",
      "Dark/Light theme support",
    ],
  },
  {
    title: "Currency Converter",
    desc: "Responsive web app to convert currencies using real-time exchange rates API.",
    longDesc:
      "A modern currency conversion tool that fetches real-time exchange rates from external APIs. Features include historical data, favorite currencies, and a clean, intuitive interface for quick conversions.",
    tags: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "REST API",
      "Async/Await",
      "Chart.js",
    ],
    live: "https://anshumankharbade.github.io/Currency-Converter/",
    github: "https://github.com/anshumankharbade/Currency-Converter",
    featured: true,
    views: 200,
    gradient: "from-orange-500/20 to-red-500/20",
    metrics: [
      {
        label: "API Speed",
        value: "0.8s",
        icon: <FaServer />,
        color: "text-green-400",
      },
      {
        label: "Accuracy",
        value: "99.9%",
        icon: <FaBolt />,
        color: "text-blue-400",
      },
      {
        label: "Countries",
        value: "150+",
        icon: <FaUsers />,
        color: "text-yellow-400",
      },
    ],
    challenges: [
      "Handling real-time API data fetching",
      "Managing multiple currency conversions",
      "Creating intuitive user interactions",
    ],
    screenshots: ["/images/currency.png", "/images/currency.png"],
    features: [
      "Real-time exchange rates",
      "150+ currency support",
      "Historical data tracking",
      "Favorite currencies list",
      "Responsive mobile design",
      "Chart visualization",
    ],
  },
  {
    title: "Tic Tac Toe Game",
    desc: "Interactive Tic Tac Toe game with score tracking, player turns, and win detection logic.",
    longDesc:
      "A modern implementation of the classic Tic Tac Toe game with enhanced features including score tracking, player statistics, game history, and responsive design. Includes AI opponent option and multiplayer mode.",
    tags: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Game Logic",
      "Responsive Design",
      "Local Storage",
    ],
    live: "https://anshumankharbade.github.io/Tic-tac-toe--game/",
    github: "https://github.com/anshumankharbade/Tic-tac-toe--game",
    featured: true,
    views: 85,
    gradient: "from-indigo-500/20 to-purple-500/20",
    metrics: [
      {
        label: "Games Played",
        value: "500+",
        icon: <FaGamepad />,
        color: "text-green-400",
      },
      {
        label: "Win Rate",
        value: "65%",
        icon: <FaTrophy />,
        color: "text-yellow-400",
      },
      {
        label: "Response Time",
        value: "0.1s",
        icon: <FaBolt />,
        color: "text-blue-400",
      },
    ],
    challenges: [
      "Implementing accurate win detection algorithm",
      "Creating smooth game state transitions",
      "Storing game history in local storage",
      "Designing responsive game board",
    ],
    screenshots: ["/images/tictactoe.png", "/images/tictactoe.png"],
    features: [
      "Two-player mode",
      "Score tracking system",
      "Win/draw detection",
      "Game history log",
      "Responsive game board",
      "Player statistics",
      "Restart/reset functionality",
    ],
  },
];

export const STATS = [
  { label: "Total Projects", value: "8+", color: "text-[#f5c518]" },
  { label: "Code Hours", value: "800+", color: "text-green-400" },
  { label: "Technologies", value: "15+", color: "text-blue-400" },
];