import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNodeJs,
  FaGitAlt,
} from "react-icons/fa";
import { SiTailwindcss, SiExpress, SiMongodb, SiPostman } from "react-icons/si";
import { TbApi } from "react-icons/tb";

export const skillCategories = [
  {
    category: "Frontend Development",
    icon: "💻",
    color: "from-blue-500/20 to-cyan-500/20",
    proficiency: "Advanced",
    skills: [
      {
        name: "HTML5",
        icon: <FaHtml5 />,
        level: 92,
        color: "#E34F26",
        proficiency: "Expert",
        description: "Semantic markup, accessibility",
      },
      {
        name: "CSS3",
        icon: <FaCss3Alt />,
        level: 90,
        color: "#1572B6",
        proficiency: "Expert",
        description: "Flexbox, Grid, responsive design",
      },
      {
        name: "JavaScript",
        icon: <FaJs />,
        level: 88,
        color: "#F7DF1E",
        proficiency: "Advanced",
        description: "ES6+, Async/Await, APIs",
      },
      {
        name: "React.js",
        icon: <FaReact />,
        level: 86,
        color: "#61DAFB",
        proficiency: "Advanced",
        description: "Hooks, Context API",
      },
      {
        name: "Tailwind CSS",
        icon: <SiTailwindcss />,
        level: 90,
        color: "#06B6D4",
        proficiency: "Expert",
        description: "Utility-first, responsive",
      },
    ],
  },
  {
    category: "Backend & Databases",
    icon: "⚙️",
    color: "from-purple-500/20 to-pink-500/20",
    proficiency: "Intermediate",
    skills: [
      {
        name: "Node.js",
        icon: <FaNodeJs />,
        level: 75,
        color: "#339933",
        proficiency: "Intermediate",
        description: "REST APIs, NPM",
      },
      {
        name: "Express.js",
        icon: <SiExpress />,
        level: 72,
        color: "#000000",
        proficiency: "Intermediate",
        description: "Middleware, routing",
      },
      {
        name: "MongoDB",
        icon: <SiMongodb />,
        level: 70,
        color: "#47A248",
        proficiency: "Intermediate",
        description: "CRUD operations",
      },
      {
        name: "REST APIs",
        icon: <TbApi />,
        level: 85,
        color: "#FF6B6B",
        proficiency: "Advanced",
        description: "Design, documentation",
      },
    ],
  },
  {
    category: "Tools & Technologies",
    icon: "🛠️",
    color: "from-green-500/20 to-emerald-500/20",
    proficiency: "Proficient",
    skills: [
      {
        name: "Git & GitHub",
        icon: <FaGitAlt />,
        level: 80,
        color: "#F05032",
        proficiency: "Advanced",
        description: "Version control",
      },
      {
        name: "VS Code",
        level: 95,
        color: "#007ACC",
        proficiency: "Expert",
        description: "Extensions, debugging",
      },
      {
        name: "Postman",
        icon: <SiPostman />,
        level: 85,
        color: "#FF6C37",
        proficiency: "Advanced",
        description: "API testing",
      },
      {
        name: "Responsive Design",
        level: 92,
        color: "#F5C518",
        proficiency: "Expert",
        description: "Mobile-first, performance",
      },
    ],
  },
];